spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      static-path-pattern: /static/**
      prefix: /templates/
      suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

